name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./package
        cp -r app ./package

    # Step 5: Package the application
    - name: Package application
      run: |
        cd package
        zip -r ../deployment-package.zip .
        cd ..

    # Step 6: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name grocery-prices-api \
          --zip-file fileb://deployment-package.zip
    
    # Step 7: Wait for the previous update to complete
    - name: Wait for update to complete
      run: |
        while true; do
          STATUS=$(aws lambda get-function-configuration --function-name grocery-prices-api --query 'State' --output text)
          if [ "$STATUS" = "Active" ]; then
            break
          fi
          echo "Waiting for Lambda function to become active..."
          sleep 10
        done
    # Step 8: Update function configuration if needed
    - name: Update function configuration
      run: |
        aws lambda update-function-configuration \
          --function-name grocery-prices-api \
          --handler app.lambda_handler \
          --runtime python3.9