name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./package
        cp -r app ./package

    # Step 4: Package the application
    - name: Package application
      run: |
        cd package
        zip -r ../deployment-package.zip .
        cd ..

    # Step 5: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        function-name: grocery-prices-api
        zip-file: deployment-package.zip